//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.ServicioLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/PracticaMVC.Models")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLogin.IServiceLoginClass")]
    public interface IServiceLoginClass {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/TraeListaClientes", ReplyAction="http://tempuri.org/IServiceLoginClass/TraeListaClientesResponse")]
        System.Collections.Generic.List<PracticaMVC.ServicioLogin.Cliente> TraeListaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/TraeListaClientes", ReplyAction="http://tempuri.org/IServiceLoginClass/TraeListaClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PracticaMVC.ServicioLogin.Cliente>> TraeListaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/RecibeRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/RecibeRegistroResponse")]
        bool RecibeRegistro(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/RecibeRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/RecibeRegistroResponse")]
        System.Threading.Tasks.Task<bool> RecibeRegistroAsync(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/EliminaRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/EliminaRegistroResponse")]
        bool EliminaRegistro(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/EliminaRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/EliminaRegistroResponse")]
        System.Threading.Tasks.Task<bool> EliminaRegistroAsync(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/ActualizaRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/ActualizaRegistroResponse")]
        bool ActualizaRegistro(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/ActualizaRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/ActualizaRegistroResponse")]
        System.Threading.Tasks.Task<bool> ActualizaRegistroAsync(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/TraeActualizarRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/TraeActualizarRegistroResponse")]
        PracticaMVC.ServicioLogin.Cliente TraeActualizarRegistro(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/TraeActualizarRegistro", ReplyAction="http://tempuri.org/IServiceLoginClass/TraeActualizarRegistroResponse")]
        System.Threading.Tasks.Task<PracticaMVC.ServicioLogin.Cliente> TraeActualizarRegistroAsync(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/traeLogin", ReplyAction="http://tempuri.org/IServiceLoginClass/traeLoginResponse")]
        bool traeLogin(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLoginClass/traeLogin", ReplyAction="http://tempuri.org/IServiceLoginClass/traeLoginResponse")]
        System.Threading.Tasks.Task<bool> traeLoginAsync(string usuario, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLoginClassChannel : PracticaMVC.ServicioLogin.IServiceLoginClass, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLoginClassClient : System.ServiceModel.ClientBase<PracticaMVC.ServicioLogin.IServiceLoginClass>, PracticaMVC.ServicioLogin.IServiceLoginClass {
        
        public ServiceLoginClassClient() {
        }
        
        public ServiceLoginClassClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLoginClassClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginClassClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginClassClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<PracticaMVC.ServicioLogin.Cliente> TraeListaClientes() {
            return base.Channel.TraeListaClientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PracticaMVC.ServicioLogin.Cliente>> TraeListaClientesAsync() {
            return base.Channel.TraeListaClientesAsync();
        }
        
        public bool RecibeRegistro(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena) {
            return base.Channel.RecibeRegistro(documento, nombre, apellido, celular, correo, usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> RecibeRegistroAsync(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena) {
            return base.Channel.RecibeRegistroAsync(documento, nombre, apellido, celular, correo, usuario, contrasena);
        }
        
        public bool EliminaRegistro(string documento) {
            return base.Channel.EliminaRegistro(documento);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaRegistroAsync(string documento) {
            return base.Channel.EliminaRegistroAsync(documento);
        }
        
        public bool ActualizaRegistro(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena) {
            return base.Channel.ActualizaRegistro(documento, nombre, apellido, celular, correo, usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizaRegistroAsync(string documento, string nombre, string apellido, string celular, string correo, string usuario, string contrasena) {
            return base.Channel.ActualizaRegistroAsync(documento, nombre, apellido, celular, correo, usuario, contrasena);
        }
        
        public PracticaMVC.ServicioLogin.Cliente TraeActualizarRegistro(string documento) {
            return base.Channel.TraeActualizarRegistro(documento);
        }
        
        public System.Threading.Tasks.Task<PracticaMVC.ServicioLogin.Cliente> TraeActualizarRegistroAsync(string documento) {
            return base.Channel.TraeActualizarRegistroAsync(documento);
        }
        
        public bool traeLogin(string usuario, string contrasena) {
            return base.Channel.traeLogin(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> traeLoginAsync(string usuario, string contrasena) {
            return base.Channel.traeLoginAsync(usuario, contrasena);
        }
    }
}
